const arr = [
    {
        name:"product-1",
        price:100,
        discount:10
    },
    {
        name:"product-2",
        price:450,
        discount:70
    },
    {
        name:"product-3",
        price:16789,
        discount:60
    },
    {
        name:"product-4",
        price:8990,
        discount:40
    },
    {
        name:"product-5",
        price:800,
        discount:60
    },
    {
        name:"product-6",
        price:8000,
        discount:20
    },
    {
        name:"product-7",
        price:2300,
        discount:20
    },
    {
        name:"product-8",
        price:5600,
        discount:30
    },
    {
        name:"product-9",
        price:34500,
        discount:50
    }
]

export default arr